spring.application.name=task2

spring.datasource.url=jdbc:postgresql://localhost:5432/task2_db
spring.datasource.username=task2_user
spring.datasource.password=task2_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.drop-first=false

logging.level.liquibase=info
logging.level.org.springframework.boot.autoconfigure.liquibase=debug

springdoc.swagger-ui.path=/swagger-ui.html